---
title: "scratch"
author: "Matthew Lam"
date: "2023-11-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## libs
```{r}
library(shiny)
library(tidyverse)
library(sf)
library(osrm)
library(tidygeocoder)
```

```{r}
address_to_coords <- function(address_text){
  address_tibble <- tibble(address=address_text)
  
  latlon <<- address_tibble %>% geocode(address=address, method="osm") %>% select(lat, long)
  
  lon <<- c(latlon$long)
  
  lat <<- c(latlon$lat)
  
  centrepoint <<- st_point(c(lon, lat)) 
  
}


address_to_coords(address)

plot(centrepoint)

centrepoint <- st_crs(centrepoint, 4326)
```

```{r}

makeisochrones <- function(lon, lat, breaksmin,breaksmax, step,osrmprofile){
  iso <<- osrmIsochrone(
    c(lon, lat), 
    breaks=seq(breaksmin, breaksmax, step),
    osrm.profile=osrmprofile
  )
  
}

makeisochrones(lon, lat, 0,15,3, "foot")

# iso <- osrmIsochrone(
#   c(lon, lat), 
#   breaks=seq(0,15,3),
#   osrm.profile="foot"
# )
# 
# plot(iso)
```


```{r}

plotmap <- function(){
  map <- tmap_shape(iso)+tm_
}
```






```{r}
# in UI part:
leafletOutput("my_tmap")

# in server part
output$my_tmap = renderLeaflet({
    tm <- tm_shape(World) + tm_polygons("HPI", legend.title = "Happy Planet Index")
    tmap_leaflet(tm)
})
```








